from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Address,Base,Employee
from faker import Faker
fake=Faker()
engine=create_engine('sqlite:///empData.db')
Base.metadata.bind=engine
DBSession =sessionmaker(bind=engine)
session = DBSession()
emp2=Employee(name='Pavan')
session.add(emp2)
session.commit()
emp2Addr=Address(street='2',zip='50002',employee=emp2)
session.add(emp2Addr)
session.commit()
emp3=Employee(name='Hruday')
session.add(emp3)
session.commit()
emp3Addr=Address(street='3',zip='50003',employee=emp3)
session.add(emp3Addr)
session.commit()
emp4=Employee(name='Virat')
session.add(emp4)
session.commit()
emp4Addr=Address(street='4',zip='50004',employee=emp4)
session.add(emp4Addr)
session.commit()
emp5=Employee(name='Rohit')
session.add(emp5)
session.commit()
emp5Addr=Address(street='5',zip='50005',employee=emp5)
session.add(emp5Addr)
session.commit()
print("Loaded Employee Data")
# emp=session.query(Address).all()
# for zip in emp:
#     print(zip.zip)
emp6=Employee(name=fake.name())
session.add(emp6)
session.commit()
emp6Addr=Address(street=fake.address(),zip=fake.address(),employee=emp6)
session.add(emp6Addr)
session.commit()
